name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  stack:
    required: true
    description: "Spacelift stack"
    default: "true"
outputs:
  result1:
    description: "Output result placeholder"
    value: "${{ inputs.param1 }}"
runs:
  using: "composite"
  steps:
    - uses: be-streamlined/action-setup-spacectl@v1.0.1
    - id: context
      shell: bash
      run: |
          echo "::set-output name=action-result::${{ inputs.param1 }}"

