name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  stack:
    required: true
    description: "Spacelift stack"
    default: "true"
outputs:
  result1:
    description: "Output result placeholder"
    value: "${{ inputs.param1 }}"
runs:
  using: "composite"
  steps:
    - name: Install spacectl
      uses: spacelift-io/setup-spacectl@main
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    - id: context
      shell: bash
      run: |
        spacectl --version
